=== montehiking/data/docs/schemas/point.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Point schema",
  "properties": {
    "coordinates": {
      "type": "array",
      "description": "point coordinates (longitude, latitude)",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "number"
      },
      "additionalProperties": false
    },
    "verified": {
      "type": "boolean",
      "description": "this point has been verified by an administrator"
    },
    "name": {
      "type": "object",
      "description": "point name",
      "properties": {
        "en": {
          "type": "string",
          "description": "english name"
        },
        "hbs": {
          "type": "string",
          "description": "native name"
        },
        "ru": {
          "type": "string",
          "description": "russian name"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "description": {
      "type": "object",
      "description": "point description",
      "properties": {
        "en": {
          "type": "string",
          "description": "english description"
        },
        "hbs": {
          "type": "string",
          "description": "native description"
        },
        "ru": {
          "type": "string",
          "description": "russian description"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "article": {
      "type": "object",
      "description": "article text",
      "properties": {
        "en": {
          "type": "array",
          "description": "english article",
          "items": {
            "type": "string"
          }
        },
        "hbs": {
          "type": "array",
          "description": "native article",
          "items": {
            "type": "string"
          }
        },
        "ru": {
          "type": "array",
          "description": "russian article",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "photos": {
      "type": "array",
      "description": "photos of the object",
      "minItems": 1,
      "maxItems": 5,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "point photo",
        "properties": {
          "filename": {
            "type": "string",
            "description": "filename with extension"
          },
          "description": {
            "type": "string",
            "description": "photo description"
          },
          "date": {
            "type": "string",
            "description": "photo date"
          },
          "copyright": {
            "type": "object",
            "description": "photo copyright",
            "properties": {
              "text": {
                "type": "string",
                "description": "copyright text"
              },
              "url": {
                "type": "string",
                "description": "copyright url"
              },
              "license": {
                "type": "string",
                "description": "license"
              },
              "year": {
                "type": "string",
                "description": "copyright year"
              }
            },
            "required": ["text"],
            "additionalProperties": false
          }
        },
        "required": ["filename"],
        "additionalProperties": false
      }
    },
    "sources": {
      "type": "array",
      "description": "links to sources of information",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "photo copyright",
        "properties": {
          "text": {
            "type": "string",
            "description": "link text"
          },
          "url": {
            "type": "string",
            "description": "link url"
          }
        },
        "required": ["url"],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "coordinates",
    "name",
    "description",
    "article",
    "photos",
    "sources"
  ],
  "additionalProperties": false
}

=== montehiking/data/docs/points/old_town/risan/index.json
{
  "coordinates": [18.695614, 42.514539],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Stari Grad Risan",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "старый квартал"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/bridge_mill/danilov_bridge/index.json
{
  "coordinates": [19.362631, 42.725436],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Danilov most",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "старинный мост"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/bridge_mill/ivanovichi_mlin/index.json
{
  "coordinates": [18.875591, 42.293835],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Stari mlin Ivanovići",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "разрушенная мельница"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/church/sv_ilije_lastva_grbaljska/index.json
{
  "coordinates": [18.811957, 42.31501],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Crkva Svetog Ilije",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "церковь XII в."
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/church/arhandjela_mihaila_herceg_novi/index.json
{
  "coordinates": [18.537594, 42.45153],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Crkva Arhanđela Mihaila",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "церковь"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/monastery/praskvica/index.json
{
  "coordinates": [18.897481, 42.262385],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Manastir Praskvica",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "древний монастырь"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/church/rodjenja_blazhene_djevice_marije_prchanj/index.json
{
  "coordinates": [18.747799, 42.453271],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Župa Rođenja Blažene Djevice Marije",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "храм"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/fortress/bucha_lukovich/index.json
{
  "coordinates": [18.696327, 42.431487],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Palata Buća-Luković",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "средневековый дворец-крепость"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}
