=== montehiking/data/docs/schemas/point.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Point schema",
  "properties": {
    "coordinates": {
      "type": "array",
      "description": "point coordinates (longitude, latitude)",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "number"
      },
      "additionalProperties": false
    },
    "verified": {
      "type": "boolean",
      "description": "this point has been verified by an administrator"
    },
    "name": {
      "type": "object",
      "description": "point name",
      "properties": {
        "en": {
          "type": "string",
          "description": "english name"
        },
        "hbs": {
          "type": "string",
          "description": "native name"
        },
        "ru": {
          "type": "string",
          "description": "russian name"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "description": {
      "type": "object",
      "description": "point description",
      "properties": {
        "en": {
          "type": "string",
          "description": "english description"
        },
        "hbs": {
          "type": "string",
          "description": "native description"
        },
        "ru": {
          "type": "string",
          "description": "russian description"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "article": {
      "type": "object",
      "description": "article text",
      "properties": {
        "en": {
          "type": "array",
          "description": "english article",
          "items": {
            "type": "string"
          }
        },
        "hbs": {
          "type": "array",
          "description": "native article",
          "items": {
            "type": "string"
          }
        },
        "ru": {
          "type": "array",
          "description": "russian article",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "photos": {
      "type": "array",
      "description": "photos of the object",
      "minItems": 1,
      "maxItems": 5,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "point photo",
        "properties": {
          "filename": {
            "type": "string",
            "description": "filename with extension"
          },
          "description": {
            "type": "string",
            "description": "photo description"
          },
          "date": {
            "type": "string",
            "description": "photo date"
          },
          "copyright": {
            "type": "object",
            "description": "photo copyright",
            "properties": {
              "text": {
                "type": "string",
                "description": "copyright text"
              },
              "url": {
                "type": "string",
                "description": "copyright url"
              },
              "license": {
                "type": "string",
                "description": "license"
              },
              "year": {
                "type": "string",
                "description": "copyright year"
              }
            },
            "required": ["text"],
            "additionalProperties": false
          }
        },
        "required": ["filename"],
        "additionalProperties": false
      }
    },
    "sources": {
      "type": "array",
      "description": "links to sources of information",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "photo copyright",
        "properties": {
          "text": {
            "type": "string",
            "description": "link text"
          },
          "url": {
            "type": "string",
            "description": "link url"
          }
        },
        "required": ["url"],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "coordinates",
    "name",
    "description",
    "article",
    "photos",
    "sources"
  ],
  "additionalProperties": false
}

=== montehiking/data/docs/points/church/sv_petra_bogdashichi/index.json
{
  "coordinates": [18.734286, 42.426339],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Crkva Svetog Petra",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "церковь XIII в."
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/old_town/donja_lastva/index.json
{
  "coordinates": [18.687084, 42.44701],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Donja Lastva",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "старый квартал"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/other/todo1/index.json
{
  "coordinates": [18.714433, 42.452559],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "заброшенная деревня?"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/bridge_mill/chelanovicha_mill/index.json
{
  "coordinates": [18.735766, 42.41693],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Uljara Čelanovića",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "старая маслиничная мельница"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/fortress/bijeli_pjesak/index.json
{
  "coordinates": [18.690072, 42.473284],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "Tvrđava Bijeli Pjesak",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "австро-венгерский форт"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/monastery/dajbabe/index.json
{
  "coordinates": [19.232471, 42.403937],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "Manastir Dajbabe",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "монастырь в катакомбах"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/nature/crno_jezero/index.json
{
  "coordinates": [19.09601, 43.147245],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Crno jezero",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "озеро"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/palace/beskucha_prchanj/index.json
{
  "coordinates": [18.753389, 42.449147],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Palata Beskuća",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "дворец Бескуча"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}
