=== montehiking/data/docs/schemas/point.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Point schema",
  "properties": {
    "coordinates": {
      "type": "array",
      "description": "point coordinates (longitude, latitude)",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "number"
      },
      "additionalProperties": false
    },
    "verified": {
      "type": "boolean",
      "description": "this point has been verified by an administrator"
    },
    "name": {
      "type": "object",
      "description": "point name",
      "properties": {
        "en": {
          "type": "string",
          "description": "english name"
        },
        "hbs": {
          "type": "string",
          "description": "native name"
        },
        "ru": {
          "type": "string",
          "description": "russian name"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "description": {
      "type": "object",
      "description": "point description",
      "properties": {
        "en": {
          "type": "string",
          "description": "english description"
        },
        "hbs": {
          "type": "string",
          "description": "native description"
        },
        "ru": {
          "type": "string",
          "description": "russian description"
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "article": {
      "type": "object",
      "description": "article text",
      "properties": {
        "en": {
          "type": "array",
          "description": "english article",
          "items": {
            "type": "string"
          }
        },
        "hbs": {
          "type": "array",
          "description": "native article",
          "items": {
            "type": "string"
          }
        },
        "ru": {
          "type": "array",
          "description": "russian article",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["en", "hbs", "ru"],
      "additionalProperties": false
    },
    "photos": {
      "type": "array",
      "description": "photos of the object",
      "minItems": 1,
      "maxItems": 5,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "point photo",
        "properties": {
          "filename": {
            "type": "string",
            "description": "filename with extension"
          },
          "description": {
            "type": "string",
            "description": "photo description"
          },
          "date": {
            "type": "string",
            "description": "photo date"
          },
          "copyright": {
            "type": "object",
            "description": "photo copyright",
            "properties": {
              "text": {
                "type": "string",
                "description": "copyright text"
              },
              "url": {
                "type": "string",
                "description": "copyright url"
              },
              "license": {
                "type": "string",
                "description": "license"
              },
              "year": {
                "type": "string",
                "description": "copyright year"
              }
            },
            "required": ["text"],
            "additionalProperties": false
          }
        },
        "required": ["filename"],
        "additionalProperties": false
      }
    },
    "sources": {
      "type": "array",
      "description": "links to sources of information",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "description": "photo copyright",
        "properties": {
          "text": {
            "type": "string",
            "description": "link text"
          },
          "url": {
            "type": "string",
            "description": "link url"
          }
        },
        "required": ["url"],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "coordinates",
    "name",
    "description",
    "article",
    "photos",
    "sources"
  ],
  "additionalProperties": false
}

=== montehiking/data/docs/points/fortress/podkuk/index.json
{
  "coordinates": [18.699166, 42.439865],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "Blokhauz Podkuk",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "австро-венгерский блокгауз"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/palace/rizzo_tivat/index.json
{
  "coordinates": [18.740058, 42.419132],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Kompleks Rizzo",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "руины имения XVI в."
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/fortress/forte_mare/index.json
{
  "coordinates": [18.535946, 42.450008],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Morska Kula (Forte Mare)",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "боснийская крепость"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/cave/magara/index.json
{
  "coordinates": [19.203216, 42.458905],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "Pećina Magara",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "пещера"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/battery/trashte_bunker/index.json
{
  "coordinates": [18.713266, 42.369541],
  "verified": false,
  "name": {
    "en": "TODO",
    "hbs": "Trašte Bunker",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "бункер с подземным ходом"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/palace/balovich_perast/index.json
{
  "coordinates": [18.7015347, 42.4851907],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Palača Balović",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "дворец XVIII в."
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/nature/gorica/index.json
{
  "coordinates": [19.276628, 42.451207],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Park Gorica",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "городской парк"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}

=== montehiking/data/docs/points/tower/redzhepagicha/index.json
{
  "coordinates": [19.946001, 42.595626],
  "verified": true,
  "name": {
    "en": "TODO",
    "hbs": "Kula Redžepagića",
    "ru": "TODO"
  },
  "description": {
    "en": "TODO",
    "hbs": "TODO",
    "ru": "средневековый дом-крепость"
  },
  "article": {
    "en": ["TODO"],
    "hbs": ["TODO"],
    "ru": ["TODO"]
  },
  "photos": [
    {
      "filename": "TODO"
    }
  ],
  "sources": []
}
